[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "clockblocks"
version = "1.0.0"
description = "A python library for synchronizing parallel and nested strands of musical time."
readme = "README.md"
requires-python = ">=3.12"
license = "GPL-3.0-only"

authors = [
    { name = "Marc Evanstein", email = "marc@marcevanstein.com" }
]

dependencies = [
    "expenvelope>=0.8.0"
]

[tool.setuptools]
zip-safe = false

[tool.setuptools.packages.find]
where = ["src"]
