[metadata]
name = cb2
description = Reimplementation of clockblocks library
long_description = file: README.md
author = Marc Evanstein
author_email = marc@marcevanstein.com
url = (in development)
license = GNU GPL Version 3
version = 0.1

[options]
zip_safe = False
packages = find:
install_requires =
    expenvelope >= 0.7.0